#!/usr/bin/env bash

validate_factor()
{
	if [ $# -ne 3 ];
	then
		args=("$@")
		count=0
		number_2=1
		for a in ${args[*]};
		do
			if [ $count -gt 1 ];
			then
				number_2=$(echo $a*$number_2 | bc)
			fi
			count=$((count + 1))
		done
	else
		number_2=$3
	fi

	number_1=$2
	number=$(echo "$1" | tr ':' '=')

	result=$(echo "if($number_2 > $number_1) 1 else 0" | bc)
	if ((result == 1)); then
		numbercp=$number_1
		number_1=$number_2
		number_2=$numbercp
	fi

	echo "$number$number_1*$number_2"
}

if [ $# -ne 1 ]
then
	echo 'Usage: rsa <file>'
	exit 1
else

	while read i
	do

		result=$(factor "$i")
		check_factor $result

	done < "$1"
fi
